"""
Seed the database with the full critical minerals catalog.
Covers: Rare Earth Elements (17), Battery Metals, Strategic Metals, PGMs.
"""
from .models.mineral import Mineral

MINERALS_DATA = [
    # ── Rare Earth Elements ── Light REE
    {
        "name": "Lanthanum", "name_zh": "镧", "symbol": "La",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 57,
        "description": "Used in nickel-metal hydride batteries, fluid cracking catalysts, optics.",
        "description_zh": "用于镍氢电池、流化催化裂化催化剂和光学玻璃。",
        "key_uses": ["NiMH batteries", "FCC catalysts", "Camera lenses", "Hydrogen storage"],
        "top_producers": ["China", "Australia", "United States"],
        "price_unit": "USD/kg (La₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Cerium", "name_zh": "铈", "symbol": "Ce",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 58,
        "description": "Most abundant rare earth; used in polishing compounds, catalysts, glass additives.",
        "description_zh": "最丰富的稀土元素，用于抛光粉、催化剂和玻璃添加剂。",
        "key_uses": ["Glass polishing", "Catalytic converters", "UV-absorbing glass", "Steel alloys"],
        "top_producers": ["China", "Australia", "India"],
        "price_unit": "USD/kg (CeO₂)",
        "criticality_score": 6,
    },
    {
        "name": "Praseodymium", "name_zh": "镨", "symbol": "Pr",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 59,
        "description": "Critical for NdPr permanent magnets used in EV motors and wind turbines.",
        "description_zh": "用于电动汽车电机和风力发电机的NdPr永磁体的关键材料。",
        "key_uses": ["NdPr magnets", "EV motors", "Wind turbines", "Fiber optic amplifiers"],
        "top_producers": ["China", "Australia", "Myanmar"],
        "price_unit": "USD/kg (Pr₆O₁₁)",
        "criticality_score": 9,
    },
    {
        "name": "Neodymium", "name_zh": "钕", "symbol": "Nd",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 60,
        "yahoo_symbol": "MP",
        "description": "Key ingredient in NdFeB permanent magnets — the strongest permanent magnets known.",
        "description_zh": "NdFeB永磁体的关键成分，是已知最强的永久磁铁。广泛用于电动汽车、风力发电机和硬盘驱动器。",
        "key_uses": ["NdFeB magnets", "EV traction motors", "Wind turbine generators", "Hard disk drives", "Speakers"],
        "top_producers": ["China", "Australia", "Myanmar", "United States"],
        "price_unit": "USD/kg (Nd₂O₃)",
        "criticality_score": 10,
    },
    {
        "name": "Samarium", "name_zh": "钐", "symbol": "Sm",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 62,
        "description": "Used in SmCo permanent magnets for high-temperature applications and nuclear reactors.",
        "description_zh": "用于高温应用的钐钴永磁体和核反应堆中子吸收体。",
        "key_uses": ["SmCo magnets", "Nuclear reactor control rods", "Aerospace"],
        "top_producers": ["China", "Australia"],
        "price_unit": "USD/kg (Sm₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Europium", "name_zh": "铕", "symbol": "Eu",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 63,
        "description": "Critical for red phosphors in LEDs, displays, and fluorescent lighting.",
        "description_zh": "LED、显示器和荧光照明中红色荧光粉的关键材料。",
        "key_uses": ["LED phosphors", "Display screens", "Anti-counterfeiting (euro banknotes)"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Eu₂O₃)",
        "criticality_score": 8,
    },
    {
        "name": "Gadolinium", "name_zh": "钆", "symbol": "Gd",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 64,
        "description": "MRI contrast agent and neutron absorber in nuclear reactors.",
        "description_zh": "核磁共振造影剂和核反应堆中子吸收体。",
        "key_uses": ["MRI contrast agents", "Nuclear reactors", "Magnetocaloric refrigeration"],
        "top_producers": ["China", "Australia"],
        "price_unit": "USD/kg (Gd₂O₃)",
        "criticality_score": 7,
    },
    # ── Rare Earth Elements ── Heavy REE
    {
        "name": "Terbium", "name_zh": "铽", "symbol": "Tb",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 65,
        "description": "Enhances NdFeB magnet performance at high temperatures; used in sonar systems.",
        "description_zh": "在高温下增强NdFeB磁体性能，用于声呐系统和绿色荧光粉。",
        "key_uses": ["High-temp NdFeB magnets", "Green phosphors", "Magneto-optical data storage", "Sonar"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Tb₄O₇)",
        "criticality_score": 10,
    },
    {
        "name": "Dysprosium", "name_zh": "镝", "symbol": "Dy",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 66,
        "description": "Essential additive in NdFeB magnets to maintain performance at high operating temperatures.",
        "description_zh": "NdFeB磁体的必要添加剂，维持高温工作性能，是电动汽车电机的关键材料。",
        "key_uses": ["EV motor magnets", "Wind turbine magnets", "Nuclear reactor control rods"],
        "top_producers": ["China", "Myanmar"],
        "price_unit": "USD/kg (Dy₂O₃)",
        "criticality_score": 10,
    },
    {
        "name": "Holmium", "name_zh": "钬", "symbol": "Ho",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 67,
        "description": "Used in fiber optic communications and medical lasers.",
        "description_zh": "用于光纤通信和医疗激光器。",
        "key_uses": ["Fiber optics", "Medical lasers", "Nuclear reactor control"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Ho₂O₃)",
        "criticality_score": 6,
    },
    {
        "name": "Erbium", "name_zh": "铒", "symbol": "Er",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 68,
        "description": "Critical for fiber optic amplifiers (EDFA) in telecommunications.",
        "description_zh": "光纤通信掺铒光纤放大器(EDFA)的关键材料。",
        "key_uses": ["Fiber optic amplifiers", "Lasers", "Pink glass tinting"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Er₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Ytterbium", "name_zh": "镱", "symbol": "Yb",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 70,
        "description": "Used in high-power fiber lasers and radiation therapy.",
        "description_zh": "用于高功率光纤激光器和癌症放射治疗。",
        "key_uses": ["Fiber lasers", "Cancer treatment", "Atomic clocks"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Yb₂O₃)",
        "criticality_score": 6,
    },
    {
        "name": "Lutetium", "name_zh": "镥", "symbol": "Lu",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 71,
        "description": "Used in PET scan detectors and cancer radiotherapy (Lu-177).",
        "description_zh": "用于PET扫描探测器和Lu-177癌症放射治疗。",
        "key_uses": ["PET scan detectors", "Cancer radiotherapy", "Oil refining catalysts"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Lu₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Scandium", "name_zh": "钪", "symbol": "Sc",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 21,
        "description": "Scandium-aluminum alloys are lightweight and high-strength for aerospace.",
        "description_zh": "钪铝合金轻质高强，用于航空航天。也用于固体氧化物燃料电池。",
        "key_uses": ["Al-Sc aerospace alloys", "Solid oxide fuel cells", "Sport equipment", "Lasers"],
        "top_producers": ["China", "Russia", "Ukraine", "Philippines"],
        "price_unit": "USD/kg (Sc₂O₃)",
        "criticality_score": 8,
    },
    {
        "name": "Yttrium", "name_zh": "钇", "symbol": "Y",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 39,
        "description": "Used in LED phosphors, superconductors, and high-performance alloys.",
        "description_zh": "用于LED荧光粉、超导体和高性能合金。",
        "key_uses": ["LED phosphors", "Microwave filters", "High-temp alloys", "Superconductors"],
        "top_producers": ["China", "Australia"],
        "price_unit": "USD/kg (Y₂O₃)",
        "criticality_score": 8,
    },
    # ── Battery & Energy Transition Metals ──
    {
        "name": "Lithium", "name_zh": "锂", "symbol": "Li",
        "category": "battery", "subcategory": "alkali_metal",
        "atomic_number": 3,
        "yahoo_symbol": "LIT",
        "description": "The cornerstone of EV battery technology. Lithium-ion batteries power EVs, smartphones, and grid storage.",
        "description_zh": "电动汽车电池技术的基石。锂离子电池为电动汽车、智能手机和电网储能提供动力。",
        "key_uses": ["EV batteries", "Grid-scale energy storage", "Portable electronics", "Ceramics & glass"],
        "top_producers": ["Australia", "Chile", "China", "Argentina"],
        "price_unit": "USD/t (LCE)",
        "criticality_score": 10,
    },
    {
        "name": "Cobalt", "name_zh": "钴", "symbol": "Co",
        "category": "battery", "subcategory": "transition_metal",
        "atomic_number": 27,
        "description": "Key cathode material in NMC/NCA lithium-ion batteries. Also used in superalloys for jet engines.",
        "description_zh": "NMC/NCA锂离子电池正极材料的关键成分，也用于航空发动机高温合金。",
        "key_uses": ["Li-ion battery cathodes", "Jet engine superalloys", "Hard metals", "Magnets"],
        "top_producers": ["DRC", "Philippines", "Russia", "Australia"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    {
        "name": "Nickel", "name_zh": "镍", "symbol": "Ni",
        "category": "battery", "subcategory": "transition_metal",
        "atomic_number": 28,
        "yahoo_symbol": "HG=F",
        "description": "Growing demand from high-nickel EV battery cathodes (NMC811). Also key for stainless steel.",
        "description_zh": "高镍NMC811电动汽车电池正极需求持续增长，也是不锈钢生产的关键原料。",
        "key_uses": ["EV battery cathodes (NMC)", "Stainless steel", "Superalloys", "Electroplating"],
        "top_producers": ["Indonesia", "Philippines", "Russia", "Canada"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    {
        "name": "Manganese", "name_zh": "锰", "symbol": "Mn",
        "category": "battery", "subcategory": "transition_metal",
        "atomic_number": 25,
        "description": "Essential for LFP and NMC batteries; also a major steelmaking additive.",
        "description_zh": "LFP和NMC电池的必要成分，也是钢铁生产的重要添加剂。",
        "key_uses": ["LFP batteries", "NMC batteries", "Steelmaking", "Aluminum alloys"],
        "top_producers": ["South Africa", "Gabon", "Australia", "China"],
        "price_unit": "USD/dmtu",
        "criticality_score": 8,
    },
    {
        "name": "Graphite", "name_zh": "石墨", "symbol": "C",
        "category": "battery", "subcategory": "non_metal",
        "description": "Dominant anode material in all lithium-ion batteries. China controls ~70% of supply.",
        "description_zh": "所有锂离子电池的主导负极材料，中国控制约70%的供应量。",
        "key_uses": ["Li-ion battery anodes", "Fuel cell bipolar plates", "Lubricants", "Nuclear reactors"],
        "top_producers": ["China", "Mozambique", "Madagascar", "Tanzania"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    # ── Strategic & Industrial Metals ──
    {
        "name": "Copper", "name_zh": "铜", "symbol": "Cu",
        "category": "strategic", "subcategory": "base_metal",
        "atomic_number": 29,
        "yahoo_symbol": "HG=F",
        "description": "The backbone of electrification. EVs use 4x more copper than ICE vehicles.",
        "description_zh": "电气化的核心金属。电动汽车使用的铜是燃油车的4倍。",
        "key_uses": ["Electrical wiring", "EV motors", "Renewable energy infrastructure", "Electronics"],
        "top_producers": ["Chile", "Peru", "DRC", "China", "Australia"],
        "price_unit": "USD/lb",
        "criticality_score": 9,
    },
    {
        "name": "Tungsten", "name_zh": "钨", "symbol": "W",
        "category": "strategic", "subcategory": "refractory_metal",
        "atomic_number": 74,
        "description": "Highest melting point of all metals. Critical for cutting tools, armor-piercing ammunition.",
        "description_zh": "所有金属中熔点最高。对切削工具和穿甲弹至关重要，中国控制约80%的供应。",
        "key_uses": ["Tungsten carbide tools", "Armor-piercing ammunition", "Aerospace alloys", "Electronics"],
        "top_producers": ["China", "Vietnam", "Russia", "Bolivia"],
        "price_unit": "USD/mtu (WO₃)",
        "criticality_score": 9,
    },
    {
        "name": "Molybdenum", "name_zh": "钼", "symbol": "Mo",
        "category": "strategic", "subcategory": "transition_metal",
        "atomic_number": 42,
        "description": "Strengthens steel alloys for high-temperature applications; used in petrochemical catalysts.",
        "description_zh": "增强高温应用的钢合金，用于石化催化剂。",
        "key_uses": ["Steel alloys", "Superalloys", "Catalysts", "Lubricants"],
        "top_producers": ["China", "United States", "Chile", "Peru"],
        "price_unit": "USD/lb",
        "criticality_score": 7,
    },
    {
        "name": "Vanadium", "name_zh": "钒", "symbol": "V",
        "category": "strategic", "subcategory": "transition_metal",
        "atomic_number": 23,
        "description": "Emerging role in vanadium redox flow batteries for grid storage; also a steel hardener.",
        "description_zh": "在电网储能钒液流电池中的作用日益重要，也用于钢铁硬化。",
        "key_uses": ["Vanadium redox batteries", "Steel hardening", "Aerospace titanium alloys"],
        "top_producers": ["China", "Russia", "South Africa", "Brazil"],
        "price_unit": "USD/lb (V₂O₅)",
        "criticality_score": 8,
    },
    {
        "name": "Gallium", "name_zh": "镓", "symbol": "Ga",
        "category": "strategic", "subcategory": "post_transition_metal",
        "atomic_number": 31,
        "description": "Essential for GaN semiconductors powering 5G, EV chargers, and radar. China export controls imposed 2023.",
        "description_zh": "GaN半导体的必要材料，为5G、电动汽车充电器和雷达提供动力。2023年中国对其实施出口管制。",
        "key_uses": ["GaN semiconductors", "5G infrastructure", "EV fast chargers", "Radar systems", "LEDs"],
        "top_producers": ["China (>80%)", "Russia", "South Korea"],
        "price_unit": "USD/kg",
        "criticality_score": 10,
    },
    {
        "name": "Germanium", "name_zh": "锗", "symbol": "Ge",
        "category": "strategic", "subcategory": "metalloid",
        "atomic_number": 32,
        "description": "Critical for fiber optic cables, infrared optics, and solar cells. China export controls 2023.",
        "description_zh": "光纤电缆、红外光学和太阳能电池的关键材料。2023年中国对其实施出口管制。",
        "key_uses": ["Fiber optic cables", "Infrared optics", "Solar cells", "Night vision"],
        "top_producers": ["China (>70%)", "Russia", "Canada"],
        "price_unit": "USD/kg",
        "criticality_score": 10,
    },
    {
        "name": "Indium", "name_zh": "铟", "symbol": "In",
        "category": "strategic", "subcategory": "post_transition_metal",
        "atomic_number": 49,
        "description": "Used in ITO transparent electrodes for touchscreens, LCDs, and CIGS solar panels.",
        "description_zh": "用于触摸屏、液晶显示器的ITO透明电极和CIGS太阳能电池。",
        "key_uses": ["ITO touchscreens", "LCD displays", "CIGS solar panels", "Semiconductors"],
        "top_producers": ["China", "South Korea", "Japan", "Canada"],
        "price_unit": "USD/kg",
        "criticality_score": 8,
    },
    {
        "name": "Chromium", "name_zh": "铬", "symbol": "Cr",
        "category": "strategic", "subcategory": "transition_metal",
        "atomic_number": 24,
        "description": "Essential for stainless steel; strategic importance for battery cathode coatings.",
        "description_zh": "不锈钢的必要成分，对电池正极涂层具有战略重要性。",
        "key_uses": ["Stainless steel", "Chromite refractories", "Aerospace superalloys"],
        "top_producers": ["South Africa", "Kazakhstan", "India", "Turkey"],
        "price_unit": "USD/t (Cr₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Aluminum", "name_zh": "铝", "symbol": "Al",
        "category": "strategic", "subcategory": "base_metal",
        "atomic_number": 13,
        "yahoo_symbol": "ALI=F",
        "description": "Most abundant metal in Earth's crust. Critical for EVs, aerospace, and packaging.",
        "description_zh": "地壳中含量最丰富的金属。对电动汽车、航空航天和包装工业至关重要。",
        "key_uses": ["EV battery casings", "Aerospace structures", "Power transmission", "Packaging"],
        "top_producers": ["China", "India", "Russia", "Canada", "UAE"],
        "price_unit": "USD/t",
        "criticality_score": 7,
    },
    # ── Platinum Group Metals ──
    {
        "name": "Silver", "name_zh": "白银", "symbol": "Ag",
        "category": "pgm", "subcategory": "noble_metal",
        "atomic_number": 47,
        "yahoo_symbol": "SI=F",
        "description": "Critical for solar panel contacts, electronics, and EV charging infrastructure.",
        "description_zh": "太阳能电池板导电接触、电子元器件和电动汽车充电基础设施的关键材料。",
        "key_uses": ["Solar PV cells", "Electronics", "EV charging", "Investment/reserves"],
        "top_producers": ["Mexico", "China", "Peru", "Chile", "Australia"],
        "price_unit": "USD/troy oz",
        "criticality_score": 7,
    },
    {
        "name": "Platinum", "name_zh": "铂", "symbol": "Pt",
        "category": "pgm", "subcategory": "pgm",
        "atomic_number": 78,
        "yahoo_symbol": "PL=F",
        "description": "Used in hydrogen fuel cells, catalytic converters, and jewelry. Key to green hydrogen economy.",
        "description_zh": "用于氢燃料电池、催化转化器和珠宝。是绿色氢经济的关键材料。",
        "key_uses": ["Hydrogen fuel cells", "Catalytic converters", "Jewelry", "Laboratory equipment"],
        "top_producers": ["South Africa", "Russia", "Zimbabwe", "Canada"],
        "price_unit": "USD/troy oz",
        "criticality_score": 9,
    },
    {
        "name": "Palladium", "name_zh": "钯", "symbol": "Pd",
        "category": "pgm", "subcategory": "pgm",
        "atomic_number": 46,
        "yahoo_symbol": "PA=F",
        "description": "Dominant metal in gasoline vehicle catalytic converters. Facing substitution pressure from EVs.",
        "description_zh": "汽油车催化转化器的主要金属，正面临电动汽车替代压力。",
        "key_uses": ["Catalytic converters", "Hydrogen purification", "Electronics"],
        "top_producers": ["Russia", "South Africa", "Canada", "Zimbabwe"],
        "price_unit": "USD/troy oz",
        "criticality_score": 8,
    },
    {
        "name": "Gold", "name_zh": "黄金", "symbol": "Au",
        "category": "pgm", "subcategory": "noble_metal",
        "atomic_number": 79,
        "yahoo_symbol": "GC=F",
        "description": "Safe-haven asset and critical for microelectronics bonding wires.",
        "description_zh": "避险资产和微电子键合线的关键材料。",
        "key_uses": ["Electronics connectors", "Investment/reserves", "Medical devices", "Aerospace"],
        "top_producers": ["China", "Australia", "Russia", "Canada", "United States"],
        "price_unit": "USD/troy oz",
        "criticality_score": 7,
    },
]


async def seed_minerals(db):
    from sqlalchemy import select
    for data in MINERALS_DATA:
        result = await db.execute(select(Mineral).where(Mineral.name == data["name"]))
        existing = result.scalar_one_or_none()
        if not existing:
            db.add(Mineral(**data))
    await db.commit()
