"""
Critical minerals catalog — 7 strategic categories per national/industry classification.
Covers 50+ minerals across energy storage, semiconductors, aerospace, defense,
industrial, chemical, and rare earth sectors.
"""
from .models.mineral import Mineral

MINERALS_DATA = [
    # ═══════════════════════════════════════════════════════════════════════
    # 1. 新能源与储能类 (energy_storage)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Lithium", "name_zh": "锂", "symbol": "Li",
        "category": "energy_storage", "subcategory": "alkali_metal",
        "atomic_number": 3,
        "yahoo_symbol": "LIT",
        "description": "The cornerstone of EV battery technology. Lithium-ion batteries power EVs, smartphones, and grid storage.",
        "description_zh": "电动汽车电池技术的基石。锂离子电池为电动汽车、智能手机和电网储能提供动力。",
        "key_uses": ["EV batteries", "Grid-scale energy storage", "Portable electronics", "Ceramics & glass"],
        "top_producers": ["Australia", "Chile", "China", "Argentina"],
        "price_unit": "USD/t (LCE)",
        "criticality_score": 10,
    },
    {
        "name": "Nickel", "name_zh": "镍", "symbol": "Ni",
        "category": "energy_storage", "subcategory": "transition_metal",
        "atomic_number": 28,
        "yahoo_symbol": "HG=F",
        "description": "Growing demand from high-nickel EV battery cathodes (NMC811). Also key for stainless steel.",
        "description_zh": "高镍NMC811电动汽车电池正极需求持续增长，也是不锈钢生产的关键原料。",
        "key_uses": ["EV battery cathodes (NMC)", "Stainless steel", "Superalloys", "Electroplating"],
        "top_producers": ["Indonesia", "Philippines", "Russia", "Canada"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    {
        "name": "Cobalt", "name_zh": "钴", "symbol": "Co",
        "category": "energy_storage", "subcategory": "transition_metal",
        "atomic_number": 27,
        "description": "Key cathode material in NMC/NCA lithium-ion batteries. Also used in superalloys for jet engines.",
        "description_zh": "NMC/NCA锂离子电池正极材料的关键成分，也用于航空发动机高温合金。",
        "key_uses": ["Li-ion battery cathodes", "Jet engine superalloys", "Hard metals", "Magnets"],
        "top_producers": ["DRC", "Philippines", "Russia", "Australia"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    {
        "name": "Graphite", "name_zh": "石墨", "symbol": "C",
        "category": "energy_storage", "subcategory": "non_metal",
        "description": "Dominant anode material in all lithium-ion batteries. China controls ~70% of supply.",
        "description_zh": "所有锂离子电池的主导负极材料，中国控制约70%的供应量。",
        "key_uses": ["Li-ion battery anodes", "Fuel cell bipolar plates", "Lubricants", "Nuclear reactors"],
        "top_producers": ["China", "Mozambique", "Madagascar", "Tanzania"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    {
        "name": "Manganese", "name_zh": "锰", "symbol": "Mn",
        "category": "energy_storage", "subcategory": "transition_metal",
        "atomic_number": 25,
        "description": "Essential for LFP and NMC batteries; also a major steelmaking additive.",
        "description_zh": "LFP和NMC电池的必要成分，也是钢铁生产的重要添加剂。",
        "key_uses": ["LFP batteries", "NMC batteries", "Steelmaking", "Aluminum alloys"],
        "top_producers": ["South Africa", "Gabon", "Australia", "China"],
        "price_unit": "USD/dmtu",
        "criticality_score": 8,
    },
    {
        "name": "Phosphorus", "name_zh": "磷", "symbol": "P",
        "category": "energy_storage", "subcategory": "non_metal",
        "atomic_number": 15,
        "description": "Critical for lithium iron phosphate (LFP) batteries and fertilizers. China dominates production.",
        "description_zh": "磷酸铁锂（LFP）电池和化肥的关键原料，中国主导全球生产。",
        "key_uses": ["LFP battery cathode", "Fertilizers", "Flame retardants", "Detergents"],
        "top_producers": ["China", "Morocco", "Russia", "Kazakhstan"],
        "price_unit": "USD/t (P₂O₅)",
        "criticality_score": 8,
    },
    {
        "name": "Fluorite", "name_zh": "萤石", "symbol": "CaF₂",
        "category": "energy_storage", "subcategory": "mineral_ore",
        "description": "Primary source of fluorine used in LiPF₆ electrolytes for lithium-ion batteries. China controls ~65%.",
        "description_zh": "锂离子电池LiPF₆电解质所需氟的主要来源，中国控制约65%的产量。",
        "key_uses": ["Battery electrolytes (LiPF₆)", "Refrigerants (HFCs)", "Aluminum smelting", "Steel flux"],
        "top_producers": ["China", "Mexico", "South Africa", "Mongolia"],
        "price_unit": "USD/t",
        "criticality_score": 8,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 2. 半导体与电子信息类 (semiconductor)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Gallium", "name_zh": "镓", "symbol": "Ga",
        "category": "semiconductor", "subcategory": "post_transition_metal",
        "atomic_number": 31,
        "description": "Essential for GaN semiconductors powering 5G, EV chargers, and radar. China export controls imposed 2023.",
        "description_zh": "GaN半导体的必要材料，为5G、电动汽车充电器和雷达提供动力。2023年中国对其实施出口管制。",
        "key_uses": ["GaN semiconductors", "5G infrastructure", "EV fast chargers", "Radar systems", "LEDs"],
        "top_producers": ["China (>80%)", "Russia", "South Korea"],
        "price_unit": "USD/kg",
        "criticality_score": 10,
    },
    {
        "name": "Germanium", "name_zh": "锗", "symbol": "Ge",
        "category": "semiconductor", "subcategory": "metalloid",
        "atomic_number": 32,
        "description": "Critical for fiber optic cables, infrared optics, and solar cells. China export controls 2023.",
        "description_zh": "光纤电缆、红外光学和太阳能电池的关键材料。2023年中国对其实施出口管制。",
        "key_uses": ["Fiber optic cables", "Infrared optics", "Solar cells", "Night vision"],
        "top_producers": ["China (>70%)", "Russia", "Canada"],
        "price_unit": "USD/kg",
        "criticality_score": 10,
    },
    {
        "name": "Indium", "name_zh": "铟", "symbol": "In",
        "category": "semiconductor", "subcategory": "post_transition_metal",
        "atomic_number": 49,
        "description": "Used in ITO transparent electrodes for touchscreens, LCDs, and CIGS solar panels.",
        "description_zh": "用于触摸屏、液晶显示器的ITO透明电极和CIGS太阳能电池。",
        "key_uses": ["ITO touchscreens", "LCD displays", "CIGS solar panels", "Semiconductors"],
        "top_producers": ["China", "South Korea", "Japan", "Canada"],
        "price_unit": "USD/kg",
        "criticality_score": 8,
    },
    {
        "name": "Silicon", "name_zh": "硅", "symbol": "Si",
        "category": "semiconductor", "subcategory": "metalloid",
        "atomic_number": 14,
        "description": "Foundation of the semiconductor industry. Ultra-pure silicon is the substrate for all microchips.",
        "description_zh": "半导体工业的基础，超纯硅是所有微芯片的基底，也是太阳能电池的核心材料。",
        "key_uses": ["Microchips & processors", "Solar PV cells", "Polysilicon wafers", "Aluminum alloys"],
        "top_producers": ["China", "Russia", "Norway", "Brazil"],
        "price_unit": "USD/kg (polysilicon)",
        "criticality_score": 9,
    },
    {
        "name": "Tantalum", "name_zh": "钽", "symbol": "Ta",
        "category": "semiconductor", "subcategory": "refractory_metal",
        "atomic_number": 73,
        "description": "Essential for miniaturized tantalum capacitors in smartphones, laptops, and aerospace electronics.",
        "description_zh": "智能手机、笔记本和航空电子设备中钽电容器的必要材料，主要产自DRC和卢旺达。",
        "key_uses": ["Tantalum capacitors", "Semiconductor manufacturing", "Superalloys", "Medical implants"],
        "top_producers": ["DRC", "Rwanda", "Brazil", "Nigeria"],
        "price_unit": "USD/kg",
        "criticality_score": 8,
    },
    {
        "name": "Niobium", "name_zh": "铌", "symbol": "Nb",
        "category": "semiconductor", "subcategory": "refractory_metal",
        "atomic_number": 41,
        "description": "Used in high-strength steel alloys and superconducting magnets for MRI machines and particle accelerators.",
        "description_zh": "用于高强度钢合金和MRI机器及粒子加速器的超导磁铁。巴西主导全球约90%的供应。",
        "key_uses": ["High-strength steel", "Superconducting magnets", "Jet engine alloys", "Capacitors"],
        "top_producers": ["Brazil", "Canada", "China"],
        "price_unit": "USD/kg (Nb₂O₅)",
        "criticality_score": 7,
    },
    {
        "name": "Beryllium", "name_zh": "铍", "symbol": "Be",
        "category": "semiconductor", "subcategory": "alkaline_earth",
        "atomic_number": 4,
        "description": "Lightest structural metal with exceptional stiffness-to-weight ratio; critical for defense electronics and X-ray windows.",
        "description_zh": "最轻的结构金属，刚度-重量比极高，对国防电子设备和X射线窗口至关重要。",
        "key_uses": ["Defense electronics", "X-ray windows", "Aerospace structures", "Nuclear reactors"],
        "top_producers": ["United States", "China", "Kazakhstan", "Mozambique"],
        "price_unit": "USD/kg",
        "criticality_score": 9,
    },
    {
        "name": "Hafnium", "name_zh": "铪", "symbol": "Hf",
        "category": "semiconductor", "subcategory": "transition_metal",
        "atomic_number": 72,
        "description": "Essential high-k dielectric material in advanced semiconductor gate oxides (sub-10nm nodes).",
        "description_zh": "先进半导体栅极氧化物（10nm以下节点）中不可或缺的高介电常数材料。",
        "key_uses": ["Semiconductor gate dielectrics", "Nuclear reactor control rods", "Superalloys", "Plasma cutting"],
        "top_producers": ["France", "Germany", "United States", "Russia"],
        "price_unit": "USD/kg",
        "criticality_score": 9,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 3. 高端装备与航空航天类 (aerospace)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Titanium", "name_zh": "钛", "symbol": "Ti",
        "category": "aerospace", "subcategory": "transition_metal",
        "atomic_number": 22,
        "description": "Exceptional strength-to-weight ratio and corrosion resistance; indispensable for aerospace and medical implants.",
        "description_zh": "极高的强度重量比和耐腐蚀性，是航空航天和医疗植入物不可或缺的材料。",
        "key_uses": ["Aircraft structures", "Jet engine components", "Medical implants", "Military armor"],
        "top_producers": ["China", "Russia", "Japan", "Kazakhstan", "Ukraine"],
        "price_unit": "USD/kg",
        "criticality_score": 9,
    },
    {
        "name": "Tungsten", "name_zh": "钨", "symbol": "W",
        "category": "aerospace", "subcategory": "refractory_metal",
        "atomic_number": 74,
        "description": "Highest melting point of all metals. Critical for cutting tools, armor-piercing ammunition.",
        "description_zh": "所有金属中熔点最高。对切削工具和穿甲弹至关重要，中国控制约80%的供应。",
        "key_uses": ["Tungsten carbide tools", "Armor-piercing ammunition", "Aerospace alloys", "Electronics"],
        "top_producers": ["China", "Vietnam", "Russia", "Bolivia"],
        "price_unit": "USD/mtu (WO₃)",
        "criticality_score": 9,
    },
    {
        "name": "Molybdenum", "name_zh": "钼", "symbol": "Mo",
        "category": "aerospace", "subcategory": "refractory_metal",
        "atomic_number": 42,
        "description": "Strengthens steel alloys for high-temperature applications; used in petrochemical catalysts.",
        "description_zh": "增强高温应用的钢合金，用于石化催化剂。",
        "key_uses": ["Steel alloys", "Superalloys", "Catalysts", "Lubricants"],
        "top_producers": ["China", "United States", "Chile", "Peru"],
        "price_unit": "USD/lb",
        "criticality_score": 7,
    },
    {
        "name": "Rhenium", "name_zh": "铼", "symbol": "Re",
        "category": "aerospace", "subcategory": "refractory_metal",
        "atomic_number": 75,
        "description": "One of the rarest metals; essential additive in single-crystal turbine blades for jet engines.",
        "description_zh": "最稀有金属之一，是喷气发动机单晶涡轮叶片的关键添加剂，无可替代。",
        "key_uses": ["Jet engine turbine blades", "Catalysts (petroleum refining)", "Superalloys", "Filaments"],
        "top_producers": ["Chile", "Poland", "United States", "Kazakhstan"],
        "price_unit": "USD/kg",
        "criticality_score": 9,
    },
    {
        "name": "Vanadium", "name_zh": "钒", "symbol": "V",
        "category": "aerospace", "subcategory": "transition_metal",
        "atomic_number": 23,
        "description": "Emerging role in vanadium redox flow batteries for grid storage; also a steel hardener.",
        "description_zh": "在电网储能钒液流电池中的作用日益重要，也用于钢铁硬化。",
        "key_uses": ["Vanadium redox batteries", "Steel hardening", "Aerospace titanium alloys"],
        "top_producers": ["China", "Russia", "South Africa", "Brazil"],
        "price_unit": "USD/lb (V₂O₅)",
        "criticality_score": 8,
    },
    {
        "name": "Chromium", "name_zh": "铬", "symbol": "Cr",
        "category": "aerospace", "subcategory": "transition_metal",
        "atomic_number": 24,
        "description": "Essential for stainless steel; strategic importance for battery cathode coatings.",
        "description_zh": "不锈钢的必要成分，对电池正极涂层具有战略重要性。",
        "key_uses": ["Stainless steel", "Chromite refractories", "Aerospace superalloys"],
        "top_producers": ["South Africa", "Kazakhstan", "India", "Turkey"],
        "price_unit": "USD/t (Cr₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Magnesium", "name_zh": "镁", "symbol": "Mg",
        "category": "aerospace", "subcategory": "alkaline_earth",
        "atomic_number": 12,
        "description": "Lightest structural metal; used in aerospace alloys, EV battery casings, and military vehicles.",
        "description_zh": "最轻的结构金属，用于航空航天合金、电动汽车电池外壳和军用车辆。中国主导产量。",
        "key_uses": ["Aerospace alloys", "EV battery casings", "Military vehicles", "Steel desulfurization"],
        "top_producers": ["China", "Russia", "Israel", "Brazil"],
        "price_unit": "USD/t",
        "criticality_score": 8,
    },
    {
        "name": "Zirconium", "name_zh": "锆", "symbol": "Zr",
        "category": "aerospace", "subcategory": "transition_metal",
        "atomic_number": 40,
        "description": "Used in nuclear fuel rod cladding and aerospace ceramics; very low neutron absorption cross-section.",
        "description_zh": "用于核燃料棒包壳和航空航天陶瓷，具有极低的中子吸收截面。",
        "key_uses": ["Nuclear fuel cladding", "Aerospace ceramics", "Chemical processing", "Medical implants"],
        "top_producers": ["Australia", "South Africa", "China", "Mozambique"],
        "price_unit": "USD/t (ZrO₂)",
        "criticality_score": 8,
    },
    {
        "name": "Platinum", "name_zh": "铂", "symbol": "Pt",
        "category": "aerospace", "subcategory": "pgm",
        "atomic_number": 78,
        "yahoo_symbol": "PL=F",
        "description": "Used in hydrogen fuel cells, catalytic converters, and jewelry. Key to green hydrogen economy.",
        "description_zh": "用于氢燃料电池、催化转化器和珠宝。是绿色氢经济的关键材料。",
        "key_uses": ["Hydrogen fuel cells", "Catalytic converters", "Jewelry", "Laboratory equipment"],
        "top_producers": ["South Africa", "Russia", "Zimbabwe", "Canada"],
        "price_unit": "USD/troy oz",
        "criticality_score": 9,
    },
    {
        "name": "Palladium", "name_zh": "钯", "symbol": "Pd",
        "category": "aerospace", "subcategory": "pgm",
        "atomic_number": 46,
        "yahoo_symbol": "PA=F",
        "description": "Dominant metal in gasoline vehicle catalytic converters. Facing substitution pressure from EVs.",
        "description_zh": "汽油车催化转化器的主要金属，正面临电动汽车替代压力。",
        "key_uses": ["Catalytic converters", "Hydrogen purification", "Electronics"],
        "top_producers": ["Russia", "South Africa", "Canada", "Zimbabwe"],
        "price_unit": "USD/troy oz",
        "criticality_score": 8,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 4. 国防军工与核工业类 (defense)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Uranium", "name_zh": "铀", "symbol": "U",
        "category": "defense", "subcategory": "actinide",
        "atomic_number": 92,
        "description": "Primary fuel for nuclear power plants generating low-carbon electricity; also weapons material.",
        "description_zh": "核电站产生低碳电力的主要燃料，哈萨克斯坦、加拿大和澳大利亚是主要生产国。",
        "key_uses": ["Nuclear power generation", "Nuclear weapons", "Medical isotope production", "Naval propulsion"],
        "top_producers": ["Kazakhstan", "Canada", "Australia", "Namibia", "Russia"],
        "price_unit": "USD/lb (U₃O₈)",
        "criticality_score": 10,
    },
    {
        "name": "Antimony", "name_zh": "锑", "symbol": "Sb",
        "category": "defense", "subcategory": "metalloid",
        "atomic_number": 51,
        "description": "Critical for flame retardants, military tracer ammunition, and infrared sensors. China export controls 2023.",
        "description_zh": "阻燃剂、军用曳光弹和红外传感器的关键材料。2023年中国对其实施出口管制。",
        "key_uses": ["Flame retardants", "Military ammunition", "Lead-acid batteries", "Infrared sensors"],
        "top_producers": ["China", "Russia", "Tajikistan", "Bolivia"],
        "price_unit": "USD/t",
        "criticality_score": 9,
    },
    {
        "name": "Tin", "name_zh": "锡", "symbol": "Sn",
        "category": "defense", "subcategory": "post_transition_metal",
        "atomic_number": 50,
        "description": "Essential for lead-free solder in all electronics PCBs; also used in advanced military systems.",
        "description_zh": "所有电子PCB无铅焊料的必要材料，也用于先进军事系统中。",
        "key_uses": ["Electronics solder", "Tin plating", "Bronze alloys", "Military electronics"],
        "top_producers": ["China", "Indonesia", "Myanmar", "Peru"],
        "price_unit": "USD/t",
        "criticality_score": 8,
    },
    {
        "name": "Bismuth", "name_zh": "铋", "symbol": "Bi",
        "category": "defense", "subcategory": "post_transition_metal",
        "atomic_number": 83,
        "description": "Lead-free replacement in military ammunition; also used in pharmaceuticals and low-melting alloys.",
        "description_zh": "军用弹药中铅的无毒替代品，也用于制药和低熔点合金。",
        "key_uses": ["Lead-free ammunition", "Pharmaceuticals", "Low-melting alloys", "Thermoelectric materials"],
        "top_producers": ["China", "Peru", "Mexico", "Bolivia"],
        "price_unit": "USD/t",
        "criticality_score": 7,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 5. 基础工业与电力基础设施类 (industrial)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Iron", "name_zh": "铁", "symbol": "Fe",
        "category": "industrial", "subcategory": "base_metal",
        "atomic_number": 26,
        "description": "Backbone of modern infrastructure. Steel demand is driven by construction, EVs, and renewable energy.",
        "description_zh": "现代基础设施的支柱，钢铁需求由建筑、电动汽车和可再生能源驱动。",
        "key_uses": ["Steel production", "Construction", "EV bodies", "Wind turbine towers"],
        "top_producers": ["Australia", "Brazil", "China", "India", "Russia"],
        "price_unit": "USD/t (62% Fe)",
        "criticality_score": 7,
    },
    {
        "name": "Copper", "name_zh": "铜", "symbol": "Cu",
        "category": "industrial", "subcategory": "base_metal",
        "atomic_number": 29,
        "yahoo_symbol": "HG=F",
        "description": "The backbone of electrification. EVs use 4x more copper than ICE vehicles.",
        "description_zh": "电气化的核心金属。电动汽车使用的铜是燃油车的4倍。",
        "key_uses": ["Electrical wiring", "EV motors", "Renewable energy infrastructure", "Electronics"],
        "top_producers": ["Chile", "Peru", "DRC", "China", "Australia"],
        "price_unit": "USD/lb",
        "criticality_score": 9,
    },
    {
        "name": "Bauxite", "name_zh": "铝土矿", "symbol": "Al₂O₃",
        "category": "industrial", "subcategory": "mineral_ore",
        "description": "Primary ore for aluminum production. Guinea holds ~25% of world reserves.",
        "description_zh": "铝生产的主要原矿，几内亚拥有全球约25%的储量，是铝供应链的关键节点。",
        "key_uses": ["Aluminum smelting", "Alumina refining", "Refractory materials", "Abrasives"],
        "top_producers": ["Australia", "Guinea", "China", "Brazil", "India"],
        "price_unit": "USD/t",
        "criticality_score": 7,
    },
    {
        "name": "Aluminum", "name_zh": "铝", "symbol": "Al",
        "category": "industrial", "subcategory": "base_metal",
        "atomic_number": 13,
        "yahoo_symbol": "ALI=F",
        "description": "Most abundant metal in Earth's crust. Critical for EVs, aerospace, and packaging.",
        "description_zh": "地壳中含量最丰富的金属。对电动汽车、航空航天和包装工业至关重要。",
        "key_uses": ["EV battery casings", "Aerospace structures", "Power transmission", "Packaging"],
        "top_producers": ["China", "India", "Russia", "Canada", "UAE"],
        "price_unit": "USD/t",
        "criticality_score": 7,
    },
    {
        "name": "Lead", "name_zh": "铅", "symbol": "Pb",
        "category": "industrial", "subcategory": "base_metal",
        "atomic_number": 82,
        "description": "Lead-acid batteries remain widely used for backup power and vehicle starting; also used in radiation shielding.",
        "description_zh": "铅酸电池广泛用于备用电源和汽车启动，也用于辐射屏蔽和弹药。",
        "key_uses": ["Lead-acid batteries", "Radiation shielding", "Ammunition", "Cable sheathing"],
        "top_producers": ["China", "Australia", "United States", "Peru", "Mexico"],
        "price_unit": "USD/t",
        "criticality_score": 6,
    },
    {
        "name": "Zinc", "name_zh": "锌", "symbol": "Zn",
        "category": "industrial", "subcategory": "base_metal",
        "atomic_number": 30,
        "description": "Galvanizing steel against corrosion; growing role in zinc-air batteries for grid storage.",
        "description_zh": "钢铁镀锌防腐的关键原料，在电网储能锌空气电池中的作用日益增长。",
        "key_uses": ["Steel galvanizing", "Zinc-air batteries", "Die casting", "Fertilizers"],
        "top_producers": ["China", "Peru", "Australia", "India", "United States"],
        "price_unit": "USD/t",
        "criticality_score": 7,
    },
    {
        "name": "Silver", "name_zh": "白银", "symbol": "Ag",
        "category": "industrial", "subcategory": "noble_metal",
        "atomic_number": 47,
        "yahoo_symbol": "SI=F",
        "description": "Critical for solar panel contacts, electronics, and EV charging infrastructure.",
        "description_zh": "太阳能电池板导电接触、电子元器件和电动汽车充电基础设施的关键材料。",
        "key_uses": ["Solar PV cells", "Electronics", "EV charging", "Investment/reserves"],
        "top_producers": ["Mexico", "China", "Peru", "Chile", "Australia"],
        "price_unit": "USD/troy oz",
        "criticality_score": 7,
    },
    {
        "name": "Gold", "name_zh": "黄金", "symbol": "Au",
        "category": "industrial", "subcategory": "noble_metal",
        "atomic_number": 79,
        "yahoo_symbol": "GC=F",
        "description": "Safe-haven asset and critical for microelectronics bonding wires.",
        "description_zh": "避险资产和微电子键合线的关键材料。",
        "key_uses": ["Electronics connectors", "Investment/reserves", "Medical devices", "Aerospace"],
        "top_producers": ["China", "Australia", "Russia", "Canada", "United States"],
        "price_unit": "USD/troy oz",
        "criticality_score": 7,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 6. 化工与现代材料类 (chemical)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Potash", "name_zh": "钾盐", "symbol": "K₂O",
        "category": "chemical", "subcategory": "mineral_ore",
        "description": "Essential fertilizer mineral for global food security. Belarus, Russia, Canada dominate supply.",
        "description_zh": "全球粮食安全的必需化肥矿物，白俄罗斯、俄罗斯和加拿大主导供应。制裁影响全球供应。",
        "key_uses": ["Potassium fertilizers", "Glass manufacturing", "Chemical industry", "Food processing"],
        "top_producers": ["Canada", "Russia", "Belarus", "China", "Germany"],
        "price_unit": "USD/t (MOP)",
        "criticality_score": 8,
    },
    {
        "name": "Sulfur", "name_zh": "硫", "symbol": "S",
        "category": "chemical", "subcategory": "non_metal",
        "atomic_number": 16,
        "description": "Primarily used as sulfuric acid feedstock for phosphate fertilizers and battery production.",
        "description_zh": "主要用作磷肥和电池生产的硫酸原料，也是橡胶硫化和化工生产的关键材料。",
        "key_uses": ["Sulfuric acid production", "Fertilizer manufacturing", "Rubber vulcanization", "Battery electrolytes"],
        "top_producers": ["China", "United States", "Russia", "Canada", "Saudi Arabia"],
        "price_unit": "USD/t",
        "criticality_score": 6,
    },
    {
        "name": "Boron", "name_zh": "硼", "symbol": "B",
        "category": "chemical", "subcategory": "metalloid",
        "atomic_number": 5,
        "description": "Neodymium-iron-boron magnets are the world's strongest permanent magnets; also used in glass and nuclear shielding.",
        "description_zh": "钕铁硼磁体是世界上最强的永磁体；也用于硼硅酸盐玻璃和核反应堆中子屏蔽。",
        "key_uses": ["NdFeB permanent magnets", "Borosilicate glass", "Fertilizers", "Nuclear reactors"],
        "top_producers": ["Turkey", "United States", "Russia", "Chile"],
        "price_unit": "USD/t (B₂O₃)",
        "criticality_score": 7,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 7. 稀土 (rare_earth) — 17 elements
    # ═══════════════════════════════════════════════════════════════════════
    {
        "name": "Lanthanum", "name_zh": "镧", "symbol": "La",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 57,
        "description": "Used in nickel-metal hydride batteries, fluid cracking catalysts, optics.",
        "description_zh": "用于镍氢电池、流化催化裂化催化剂和光学玻璃。",
        "key_uses": ["NiMH batteries", "FCC catalysts", "Camera lenses", "Hydrogen storage"],
        "top_producers": ["China", "Australia", "United States"],
        "price_unit": "USD/kg (La₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Cerium", "name_zh": "铈", "symbol": "Ce",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 58,
        "description": "Most abundant rare earth; used in polishing compounds, catalysts, glass additives.",
        "description_zh": "最丰富的稀土元素，用于抛光粉、催化剂和玻璃添加剂。",
        "key_uses": ["Glass polishing", "Catalytic converters", "UV-absorbing glass", "Steel alloys"],
        "top_producers": ["China", "Australia", "India"],
        "price_unit": "USD/kg (CeO₂)",
        "criticality_score": 6,
    },
    {
        "name": "Praseodymium", "name_zh": "镨", "symbol": "Pr",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 59,
        "description": "Critical for NdPr permanent magnets used in EV motors and wind turbines.",
        "description_zh": "用于电动汽车电机和风力发电机的NdPr永磁体的关键材料。",
        "key_uses": ["NdPr magnets", "EV motors", "Wind turbines", "Fiber optic amplifiers"],
        "top_producers": ["China", "Australia", "Myanmar"],
        "price_unit": "USD/kg (Pr₆O₁₁)",
        "criticality_score": 9,
    },
    {
        "name": "Neodymium", "name_zh": "钕", "symbol": "Nd",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 60,
        "yahoo_symbol": "MP",
        "description": "Key ingredient in NdFeB permanent magnets — the strongest permanent magnets known.",
        "description_zh": "NdFeB永磁体的关键成分，是已知最强的永久磁铁。广泛用于电动汽车、风力发电机和硬盘驱动器。",
        "key_uses": ["NdFeB magnets", "EV traction motors", "Wind turbine generators", "Hard disk drives"],
        "top_producers": ["China", "Australia", "Myanmar", "United States"],
        "price_unit": "USD/kg (Nd₂O₃)",
        "criticality_score": 10,
    },
    {
        "name": "Promethium", "name_zh": "钷", "symbol": "Pm",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 61,
        "description": "Radioactive REE with no stable isotopes; used in pacemakers, luminous paint, and thickness gauges.",
        "description_zh": "无稳定同位素的放射性稀土元素，用于心脏起搏器、发光涂料和厚度测量仪器。",
        "key_uses": ["Nuclear batteries (pacemakers)", "Luminous paint", "Thickness gauges", "X-ray sources"],
        "top_producers": ["Russia", "United States"],
        "price_unit": "USD/g",
        "criticality_score": 6,
    },
    {
        "name": "Samarium", "name_zh": "钐", "symbol": "Sm",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 62,
        "description": "Used in SmCo permanent magnets for high-temperature applications and nuclear reactors.",
        "description_zh": "用于高温应用的钐钴永磁体和核反应堆中子吸收体。",
        "key_uses": ["SmCo magnets", "Nuclear reactor control rods", "Aerospace"],
        "top_producers": ["China", "Australia"],
        "price_unit": "USD/kg (Sm₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Europium", "name_zh": "铕", "symbol": "Eu",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 63,
        "description": "Critical for red phosphors in LEDs, displays, and fluorescent lighting.",
        "description_zh": "LED、显示器和荧光照明中红色荧光粉的关键材料。",
        "key_uses": ["LED phosphors", "Display screens", "Anti-counterfeiting (euro banknotes)"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Eu₂O₃)",
        "criticality_score": 8,
    },
    {
        "name": "Gadolinium", "name_zh": "钆", "symbol": "Gd",
        "category": "rare_earth", "subcategory": "LREE",
        "atomic_number": 64,
        "description": "MRI contrast agent and neutron absorber in nuclear reactors.",
        "description_zh": "核磁共振造影剂和核反应堆中子吸收体。",
        "key_uses": ["MRI contrast agents", "Nuclear reactors", "Magnetocaloric refrigeration"],
        "top_producers": ["China", "Australia"],
        "price_unit": "USD/kg (Gd₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Terbium", "name_zh": "铽", "symbol": "Tb",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 65,
        "description": "Enhances NdFeB magnet performance at high temperatures; used in sonar systems.",
        "description_zh": "在高温下增强NdFeB磁体性能，用于声呐系统和绿色荧光粉。",
        "key_uses": ["High-temp NdFeB magnets", "Green phosphors", "Magneto-optical data storage", "Sonar"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Tb₄O₇)",
        "criticality_score": 10,
    },
    {
        "name": "Dysprosium", "name_zh": "镝", "symbol": "Dy",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 66,
        "description": "Essential additive in NdFeB magnets to maintain performance at high operating temperatures.",
        "description_zh": "NdFeB磁体的必要添加剂，维持高温工作性能，是电动汽车电机的关键材料。",
        "key_uses": ["EV motor magnets", "Wind turbine magnets", "Nuclear reactor control rods"],
        "top_producers": ["China", "Myanmar"],
        "price_unit": "USD/kg (Dy₂O₃)",
        "criticality_score": 10,
    },
    {
        "name": "Holmium", "name_zh": "钬", "symbol": "Ho",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 67,
        "description": "Used in fiber optic communications and medical lasers.",
        "description_zh": "用于光纤通信和医疗激光器。",
        "key_uses": ["Fiber optics", "Medical lasers", "Nuclear reactor control"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Ho₂O₃)",
        "criticality_score": 6,
    },
    {
        "name": "Erbium", "name_zh": "铒", "symbol": "Er",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 68,
        "description": "Critical for fiber optic amplifiers (EDFA) in telecommunications.",
        "description_zh": "光纤通信掺铒光纤放大器(EDFA)的关键材料。",
        "key_uses": ["Fiber optic amplifiers", "Lasers", "Pink glass tinting"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Er₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Thulium", "name_zh": "铥", "symbol": "Tm",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 69,
        "description": "Rarest naturally occurring REE; used in portable X-ray machines and high-power lasers.",
        "description_zh": "自然界最稀有的稀土元素，用于便携式X射线机和高功率激光器。",
        "key_uses": ["Portable X-ray machines", "High-power lasers", "Surgical lasers"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Tm₂O₃)",
        "criticality_score": 6,
    },
    {
        "name": "Ytterbium", "name_zh": "镱", "symbol": "Yb",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 70,
        "description": "Used in high-power fiber lasers and radiation therapy.",
        "description_zh": "用于高功率光纤激光器和癌症放射治疗。",
        "key_uses": ["Fiber lasers", "Cancer treatment", "Atomic clocks"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Yb₂O₃)",
        "criticality_score": 6,
    },
    {
        "name": "Lutetium", "name_zh": "镥", "symbol": "Lu",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 71,
        "description": "Used in PET scan detectors and cancer radiotherapy (Lu-177).",
        "description_zh": "用于PET扫描探测器和Lu-177癌症放射治疗。",
        "key_uses": ["PET scan detectors", "Cancer radiotherapy", "Oil refining catalysts"],
        "top_producers": ["China"],
        "price_unit": "USD/kg (Lu₂O₃)",
        "criticality_score": 7,
    },
    {
        "name": "Scandium", "name_zh": "钪", "symbol": "Sc",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 21,
        "description": "Scandium-aluminum alloys are lightweight and high-strength for aerospace.",
        "description_zh": "钪铝合金轻质高强，用于航空航天。也用于固体氧化物燃料电池。",
        "key_uses": ["Al-Sc aerospace alloys", "Solid oxide fuel cells", "Sport equipment", "Lasers"],
        "top_producers": ["China", "Russia", "Ukraine", "Philippines"],
        "price_unit": "USD/kg (Sc₂O₃)",
        "criticality_score": 8,
    },
    {
        "name": "Yttrium", "name_zh": "钇", "symbol": "Y",
        "category": "rare_earth", "subcategory": "HREE",
        "atomic_number": 39,
        "description": "Used in LED phosphors, superconductors, and high-performance alloys.",
        "description_zh": "用于LED荧光粉、超导体和高性能合金。",
        "key_uses": ["LED phosphors", "Microwave filters", "High-temp alloys", "Superconductors"],
        "top_producers": ["China", "Australia"],
        "price_unit": "USD/kg (Y₂O₃)",
        "criticality_score": 8,
    },
]


async def seed_minerals(db):
    """Upsert minerals — inserts new records and updates category/data for existing ones."""
    from sqlalchemy import select
    for data in MINERALS_DATA:
        result = await db.execute(select(Mineral).where(Mineral.name == data["name"]))
        existing = result.scalar_one_or_none()
        if not existing:
            db.add(Mineral(**data))
        else:
            for k, v in data.items():
                if k != "name":
                    setattr(existing, k, v)
    await db.commit()
